// backend/lib/geoData.js
// Comprehensive country + state data

const COUNTRIES = [
  { code:'AF', name:'Afghanistan',          dialCode:'+93',  flag:'🇦🇫' },
  { code:'AL', name:'Albania',              dialCode:'+355', flag:'🇦🇱' },
  { code:'DZ', name:'Algeria',              dialCode:'+213', flag:'🇩🇿' },
  { code:'AR', name:'Argentina',            dialCode:'+54',  flag:'🇦🇷' },
  { code:'AU', name:'Australia',            dialCode:'+61',  flag:'🇦🇺' },
  { code:'AT', name:'Austria',              dialCode:'+43',  flag:'🇦🇹' },
  { code:'BD', name:'Bangladesh',           dialCode:'+880', flag:'🇧🇩' },
  { code:'BE', name:'Belgium',              dialCode:'+32',  flag:'🇧🇪' },
  { code:'BR', name:'Brazil',               dialCode:'+55',  flag:'🇧🇷' },
  { code:'CA', name:'Canada',               dialCode:'+1',   flag:'🇨🇦' },
  { code:'CL', name:'Chile',                dialCode:'+56',  flag:'🇨🇱' },
  { code:'CN', name:'China',                dialCode:'+86',  flag:'🇨🇳' },
  { code:'CO', name:'Colombia',             dialCode:'+57',  flag:'🇨🇴' },
  { code:'CY', name:'Cyprus',               dialCode:'+357', flag:'🇨🇾' },
  { code:'CZ', name:'Czech Republic',       dialCode:'+420', flag:'🇨🇿' },
  { code:'DK', name:'Denmark',              dialCode:'+45',  flag:'🇩🇰' },
  { code:'EG', name:'Egypt',                dialCode:'+20',  flag:'🇪🇬' },
  { code:'EE', name:'Estonia',              dialCode:'+372', flag:'🇪🇪' },
  { code:'ET', name:'Ethiopia',             dialCode:'+251', flag:'🇪🇹' },
  { code:'FI', name:'Finland',              dialCode:'+358', flag:'🇫🇮' },
  { code:'FR', name:'France',               dialCode:'+33',  flag:'🇫🇷' },
  { code:'DE', name:'Germany',              dialCode:'+49',  flag:'🇩🇪' },
  { code:'GH', name:'Ghana',                dialCode:'+233', flag:'🇬🇭' },
  { code:'GR', name:'Greece',               dialCode:'+30',  flag:'🇬🇷' },
  { code:'HK', name:'Hong Kong',            dialCode:'+852', flag:'🇭🇰' },
  { code:'HU', name:'Hungary',              dialCode:'+36',  flag:'🇭🇺' },
  { code:'IN', name:'India',                dialCode:'+91',  flag:'🇮🇳' },
  { code:'ID', name:'Indonesia',            dialCode:'+62',  flag:'🇮🇩' },
  { code:'IE', name:'Ireland',              dialCode:'+353', flag:'🇮🇪' },
  { code:'IL', name:'Israel',               dialCode:'+972', flag:'🇮🇱' },
  { code:'IT', name:'Italy',                dialCode:'+39',  flag:'🇮🇹' },
  { code:'JP', name:'Japan',                dialCode:'+81',  flag:'🇯🇵' },
  { code:'JO', name:'Jordan',               dialCode:'+962', flag:'🇯🇴' },
  { code:'KE', name:'Kenya',                dialCode:'+254', flag:'🇰🇪' },
  { code:'KW', name:'Kuwait',               dialCode:'+965', flag:'🇰🇼' },
  { code:'LV', name:'Latvia',               dialCode:'+371', flag:'🇱🇻' },
  { code:'LB', name:'Lebanon',              dialCode:'+961', flag:'🇱🇧' },
  { code:'LT', name:'Lithuania',            dialCode:'+370', flag:'🇱🇹' },
  { code:'MY', name:'Malaysia',             dialCode:'+60',  flag:'🇲🇾' },
  { code:'MV', name:'Maldives',             dialCode:'+960', flag:'🇲🇻' },
  { code:'MX', name:'Mexico',               dialCode:'+52',  flag:'🇲🇽' },
  { code:'NL', name:'Netherlands',          dialCode:'+31',  flag:'🇳🇱' },
  { code:'NZ', name:'New Zealand',          dialCode:'+64',  flag:'🇳🇿' },
  { code:'NG', name:'Nigeria',              dialCode:'+234', flag:'🇳🇬' },
  { code:'NO', name:'Norway',               dialCode:'+47',  flag:'🇳🇴' },
  { code:'OM', name:'Oman',                 dialCode:'+968', flag:'🇴🇲' },
  { code:'PK', name:'Pakistan',             dialCode:'+92',  flag:'🇵🇰' },
  { code:'PH', name:'Philippines',          dialCode:'+63',  flag:'🇵🇭' },
  { code:'PL', name:'Poland',               dialCode:'+48',  flag:'🇵🇱' },
  { code:'PT', name:'Portugal',             dialCode:'+351', flag:'🇵🇹' },
  { code:'QA', name:'Qatar',                dialCode:'+974', flag:'🇶🇦' },
  { code:'RO', name:'Romania',              dialCode:'+40',  flag:'🇷🇴' },
  { code:'RU', name:'Russia',               dialCode:'+7',   flag:'🇷🇺' },
  { code:'SA', name:'Saudi Arabia',         dialCode:'+966', flag:'🇸🇦' },
  { code:'SG', name:'Singapore',            dialCode:'+65',  flag:'🇸🇬' },
  { code:'ZA', name:'South Africa',         dialCode:'+27',  flag:'🇿🇦' },
  { code:'KR', name:'South Korea',          dialCode:'+82',  flag:'🇰🇷' },
  { code:'ES', name:'Spain',                dialCode:'+34',  flag:'🇪🇸' },
  { code:'LK', name:'Sri Lanka',            dialCode:'+94',  flag:'🇱🇰' },
  { code:'SE', name:'Sweden',               dialCode:'+46',  flag:'🇸🇪' },
  { code:'CH', name:'Switzerland',          dialCode:'+41',  flag:'🇨🇭' },
  { code:'TW', name:'Taiwan',               dialCode:'+886', flag:'🇹🇼' },
  { code:'TZ', name:'Tanzania',             dialCode:'+255', flag:'🇹🇿' },
  { code:'TH', name:'Thailand',             dialCode:'+66',  flag:'🇹🇭' },
  { code:'TR', name:'Turkey',               dialCode:'+90',  flag:'🇹🇷' },
  { code:'UG', name:'Uganda',               dialCode:'+256', flag:'🇺🇬' },
  { code:'UA', name:'Ukraine',              dialCode:'+380', flag:'🇺🇦' },
  { code:'AE', name:'United Arab Emirates', dialCode:'+971', flag:'🇦🇪' },
  { code:'GB', name:'United Kingdom',       dialCode:'+44',  flag:'🇬🇧' },
  { code:'US', name:'United States',        dialCode:'+1',   flag:'🇺🇸' },
  { code:'VN', name:'Vietnam',              dialCode:'+84',  flag:'🇻🇳' },
  { code:'ZM', name:'Zambia',               dialCode:'+260', flag:'🇿🇲' },
  { code:'ZW', name:'Zimbabwe',             dialCode:'+263', flag:'🇿🇼' },
];

const STATES_BY_COUNTRY = {
  IN: ['Andhra Pradesh','Arunachal Pradesh','Assam','Bihar','Chhattisgarh','Goa','Gujarat','Haryana','Himachal Pradesh','Jharkhand','Karnataka','Kerala','Madhya Pradesh','Maharashtra','Manipur','Meghalaya','Mizoram','Nagaland','Odisha','Punjab','Rajasthan','Sikkim','Tamil Nadu','Telangana','Tripura','Uttar Pradesh','Uttarakhand','West Bengal','Andaman and Nicobar Islands','Chandigarh','Dadra and Nagar Haveli and Daman and Diu','Delhi','Jammu and Kashmir','Ladakh','Lakshadweep','Puducherry'],
  US: ['Alabama','Alaska','Arizona','Arkansas','California','Colorado','Connecticut','Delaware','Florida','Georgia','Hawaii','Idaho','Illinois','Indiana','Iowa','Kansas','Kentucky','Louisiana','Maine','Maryland','Massachusetts','Michigan','Minnesota','Mississippi','Missouri','Montana','Nebraska','Nevada','New Hampshire','New Jersey','New Mexico','New York','North Carolina','North Dakota','Ohio','Oklahoma','Oregon','Pennsylvania','Rhode Island','South Carolina','South Dakota','Tennessee','Texas','Utah','Vermont','Virginia','Washington','West Virginia','Wisconsin','Wyoming','Washington DC'],
  AU: ['New South Wales','Victoria','Queensland','Western Australia','South Australia','Tasmania','Australian Capital Territory','Northern Territory'],
  CA: ['Alberta','British Columbia','Manitoba','New Brunswick','Newfoundland and Labrador','Northwest Territories','Nova Scotia','Nunavut','Ontario','Prince Edward Island','Quebec','Saskatchewan','Yukon'],
  GB: ['England','Scotland','Wales','Northern Ireland'],
  AE: ['Abu Dhabi','Dubai','Sharjah','Ajman','Umm Al-Quwain','Ras Al Khaimah','Fujairah'],
  SA: ['Riyadh','Makkah','Madinah','Eastern Province','Asir','Tabuk','Hail','Northern Borders','Jizan','Najran','Al Bahah','Al Jouf','Qassim'],
  PK: ['Punjab','Sindh','Khyber Pakhtunkhwa','Balochistan','Azad Kashmir','Gilgit-Baltistan','Islamabad Capital Territory'],
  BD: ['Dhaka','Chittagong','Rajshahi','Khulna','Barisal','Sylhet','Rangpur','Mymensingh'],
  LK: ['Western','Central','Southern','Northern','Eastern','North Western','North Central','Uva','Sabaragamuwa'],
  SG: ['Central Region','East Region','North Region','North-East Region','West Region'],
  MY: ['Johor','Kedah','Kelantan','Kuala Lumpur','Labuan','Malacca','Negeri Sembilan','Pahang','Penang','Perak','Perlis','Putrajaya','Sabah','Sarawak','Selangor','Terengganu'],
  PH: ['Metro Manila','Luzon','Visayas','Mindanao','Calabarzon','Central Luzon','Western Visayas','Central Visayas','Davao','Northern Mindanao','Soccsksargen'],
  ID: ['Jakarta','West Java','East Java','Central Java','Banten','North Sumatra','South Sulawesi','West Kalimantan','East Kalimantan','Bali','Riau','South Sumatra'],
  TH: ['Bangkok','Chiang Mai','Phuket','Pattaya','Nonthaburi','Nakhon Ratchasima','Khon Kaen','Hat Yai','Chonburi','Rayong'],
  VN: ['Ho Chi Minh City','Hanoi','Da Nang','Hai Phong','Can Tho','Bien Hoa','Hue','Nha Trang','Vung Tau','Quy Nhon'],
  CN: ['Beijing','Shanghai','Guangdong','Sichuan','Zhejiang','Jiangsu','Henan','Hubei','Hunan','Shandong','Yunnan','Fujian','Anhui'],
  JP: ['Tokyo','Osaka','Kyoto','Nagoya','Sapporo','Fukuoka','Kobe','Kawasaki','Saitama','Hiroshima'],
  KR: ['Seoul','Busan','Incheon','Daegu','Daejeon','Gwangju','Suwon','Ulsan','Sejong','Jeju'],
  DE: ['Bavaria','North Rhine-Westphalia','Baden-Württemberg','Lower Saxony','Hesse','Saxony','Berlin','Hamburg','Rhineland-Palatinate','Schleswig-Holstein'],
  FR: ['Île-de-France','Auvergne-Rhône-Alpes','Occitanie','Nouvelle-Aquitaine','Hauts-de-France','Provence-Alpes-Côte d\'Azur','Grand Est','Pays de la Loire','Normandie','Bretagne'],
  IT: ['Lombardy','Lazio','Campania','Sicily','Veneto','Emilia-Romagna','Piedmont','Apulia','Tuscany','Calabria'],
  ES: ['Catalonia','Community of Madrid','Andalusia','Valencia','Galicia','Castile and León','Basque Country','Canary Islands','Castilla-La Mancha','Aragon'],
  BR: ['São Paulo','Rio de Janeiro','Minas Gerais','Bahia','Paraná','Rio Grande do Sul','Pernambuco','Ceará','Pará','Santa Catarina'],
  MX: ['Mexico City','Jalisco','Nuevo León','Veracruz','Puebla','Guanajuato','Chiapas','Chihuahua','Michoacán','Oaxaca'],
  ZA: ['Gauteng','Western Cape','KwaZulu-Natal','Eastern Cape','Limpopo','Mpumalanga','North West','Free State','Northern Cape'],
  NG: ['Lagos','Kano','Abuja','Ibadan','Kaduna','Port Harcourt','Enugu','Benin City','Maiduguri','Zaria'],
  EG: ['Cairo','Giza','Alexandria','Luxor','Aswan','Mansoura','Suez','Port Said','Tanta','Sharm el-Sheikh'],
  KE: ['Nairobi','Mombasa','Kisumu','Nakuru','Eldoret','Thika','Malindi','Nyeri','Garissa','Kakamega'],
  QA: ['Doha','Al Rayyan','Al Wakrah','Al Khor','Umm Salal','Al Shamal','Madinat ash Shamal','Al Sheehaniya'],
  KW: ['Al Ahmadi','Hawalli','Farwaniya','Mubarak Al-Kabeer','Capital','Jahra'],
  OM: ['Muscat','Dhofar','Batinah North','Batinah South','Dakhliyah','Sharqiyah North','Sharqiyah South','Dhahirah','Buraimi','Wusta'],
  JO: ['Amman','Zarqa','Irbid','Mafraq','Aqaba','Madaba','Jerash','Salt','Karak','Tafileh'],
};

module.exports = { COUNTRIES, STATES_BY_COUNTRY };
